global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
- job_name: myapp
  static_configs:
  - targets: ["172.18.0.1:9000"]
    labels:
      path: "/api/metrics"
  metrics_path: /api/metrics